version: '3.7'

services:
  app-db:
    image: postgres
    container_name: app-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: stops_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: welcome1

  web-client:
    build:
      context: ./public-transport-web-server
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - '8080:8080'
    environment:
      PROFILE: dev-docker
      JAVA_OPTS: -Xmx1G
    depends_on:
      - app-db

#  gtfs-warszawa:
#    build:
#      context: ../public-transport-otp
#      dockerfile: Dockerfile.warszawa
#    container_name: gtfs-warszawa
#    ports:
#      - '8082:8080'
#    environment:
#      - JAVA_OPTS=-Xmx5G

#  otp_berlin:
#    image: docker.io/opentripplanner/opentripplanner:latest
#    container_name: otp_berlin
#    ports:
#      - '8082:8080'
#    environment:
#      - JAVA_OPTS=-Xmx5G
#      -

        #  docker run -it --rm -p 8080:8080 -e JAVA_TOOL_OPTIONS='-Xmx10g' -v "$(pwd)/berlin:/var/opentripplanner" docker.io/opentripplanner/opentripplanner:latest --build --serve

#  gtfs-krakow:
#    build:
#      context: ../public-transport-otp
#      dockerfile: Dockerfile.krakow
#    container_name: gtfs-krakow
#    networks:
#      - gtfs_network
#    ports:
#      - '8084:8080'
#    environment:
#      - JAVA_OPTS=-Xmx2G
