version: '3.7'

services:
  web-client:
    build:
      context: ./public-transport-web-server
      dockerfile: Dockerfile
    container_name: web-client
    networks:
      - gtfs_network
    ports:
      - '8080:8080'
    environment:
      PROFILE: dev-docker
      JAVA_OPTS: -Xmx1G
    depends_on:
      - gtfs-warszawa

  gtfs-warszawa:
    build:
      context: ../public-transport-otp
      dockerfile: Dockerfile.warszawa
    container_name: gtfs-warszawa
    networks:
      - gtfs_network
    ports:
      - '8082:8080'
    environment:
      - JAVA_OPTS=-Xmx5G

#  gtfs-krakow:
#    build:
#      context: ../public-transport-otp
#      dockerfile: Dockerfile.krakow
#    container_name: gtfs-krakow
#    networks:
#      - gtfs_network
#    ports:
#      - '8084:8080'
#    environment:
#      - JAVA_OPTS=-Xmx2G

networks:
  gtfs_network:
    driver: bridge
