spring.datasource.url=jdbc:postgresql://app-db:5432/public_transport_db
spring.datasource.username=${GHA_SECRET_DB_USERNAME}
spring.datasource.password=${GHA_SECRET_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
