openapi: 3.0.0
info:

paths:
  /agency/{agency}/brigades:
    get:
      tags:
        - brigade
      summary: Get list of brigades
      operationId: getBrigades
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBrigadeResponse'

    post:
      tags:
        - brigade
      summary: Create new brigade
      operationId: createBrigade
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrigadeBody'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '../public-transport-api.yaml/#/components/schemas/Status'

    put:
      tags:
        - brigade
      summary: Update brigade
      operationId: updateBrigade
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrigadePatchBody'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '../public-transport-api.yaml/#/components/schemas/Status'

    delete:
      tags:
        - brigade
      summary: Delete brigade
      operationId: deleteBrigade
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrigadeDeleteBody'
      responses:
        200:
          description: DELETED
          content:
            application/json:
              schema:
                $ref: '../public-transport-api.yaml/#/components/schemas/Status'

  /agency/{agency}/brigades/{brigadeCode}/details:
    get:
      tags:
        - brigade
      summary: Get brigade item details by brigade code
      operationId: getBrigadeDetails
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: brigadeCode
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBrigadeDetailsResponse'

  /agency/{agency}/calendar/{calendarCode}/symbol/{calendarSymbol}/brigade:
    post:
      tags:
        - brigade
      summary: Create brigade for calendar symbol
      operationId: createCalendarSymbolBrigade
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: calendarCode
          required: true
          schema:
            type: string
        - in: path
          name: calendarSymbol
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCalendarSymbolBrigadeRequest'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCalendarSymbolBrigadeResponse'

  /agency/{agency}/brigades/{brigadeCode}/calendar/{calendarCode}/symbol/{symbol}/resource:
    get:
      tags:
        - brigade
      summary: Get brigade resources for calendar symbol
      operationId: getCalendarSymbolBrigadeResources
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: brigadeCode
          required: true
          schema:
            type: string
        - in: path
          name: calendarCode
          required: true
          schema:
            type: string
        - in: path
          name: symbol
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrigadeBodyV2'

    post:
      tags:
        - brigade
      summary: Get next calendar resource sequence
      operationId: getNextCalendarResourceSequence
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: brigadeCode
          required: true
          schema:
            type: string
        - in: path
          name: calendarCode
          required: true
          schema:
            type: string
        - in: path
          name: symbol
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NextCalendarResourceSequenceResponse'

  /agency/{agency}/brigades/{brigadeCode}/calendar/{calendarCode}/symbol/{symbol}/resource/{resourceCode}/event:
    post:
      tags:
        - brigade
      summary: Get next brigade event sequence
      operationId: getNextBrigadeEventSequence
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: brigadeCode
          required: true
          schema:
            type: string
        - in: path
          name: calendarCode
          required: true
          schema:
            type: string
        - in: path
          name: symbol
          required: true
          schema:
            type: string
        - in: path
          name: resourceCode
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NextBrigadeEventSequenceResponse'

    put:
      tags:
        - brigade
      summary: Create brigade event for resource
      operationId: putBrigadeEvent
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
        - in: path
          name: brigadeCode
          required: true
          schema:
            type: string
        - in: path
          name: calendarCode
          required: true
          schema:
            type: string
        - in: path
          name: symbol
          required: true
          schema:
            type: string
        - in: path
          name: resourceCode
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutBrigadeEventBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '../public-transport-api.yaml/#/components/schemas/Status'

components:
  schemas:
    CreateCalendarSymbolBrigadeRequest:
      type: object
      required:
        - calendarSymbolId
        - brigadeName
      properties:
        calendarSymbolId:
          $ref: '../public-transport-core.yaml#/components/schemas/CalendarSymbolId'
        brigadeName:
          type: string

    CreateCalendarSymbolBrigadeResponse:
      type: object
      properties:
        status:
          $ref: '../public-transport-api.yaml/#/components/schemas/Status'

    NextCalendarResourceSequenceResponse:
      type: object
      properties:
        sequence:
          type: integer
        sequenceHex:
          type: string

    NextBrigadeEventSequenceResponse:
      type: object
      properties:
        sequence:
          type: integer
        sequenceHex:
          type: string

    PutBrigadeEventBody:
      type: object
      properties:
        startSecond:
          type: integer
        endSecond:
          type: integer
        line:
          type: string
        name:
          type: string
        sequence:
          type: integer
        sequenceHex:
          type: string

    BrigadeEvent:
      type: object
      properties:
        startSecond:
          type: integer
        endSecond:
          type: integer
        line:
          type: string
        name:
          type: string
        sequence:
          type: integer
        sequenceHex:
          type: string

    BrigadeItemBody:
      type: object
      properties:
        name:
          type: string
        sequence:
          type: integer
        sequenceHex:
          type: string
        brigades:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeBodyV2'

    GetBrigadeDetailsResponse:
      type: object
      properties:
        brigade:
          $ref: '#/components/schemas/BrigadeItemBody'

    GetBrigadeResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeItemBody'

    BrigadeTrip:
      type: object
      properties:
        tripId:
          $ref: '../public-transport-core.yaml#/components/schemas/TripId'
        tripSequence:
          type: integer
        origin:
          type: string
        destination:
          type: string
        travelTimeInSeconds:
          type: integer
        arrivalTime:
          type: integer
        departureTime:
          type: integer

    BrigadeBody:
      type: object
      properties:
        brigadeName:
          type: string
        calendarSymbolId:
          $ref: '../public-transport-core.yaml#/components/schemas/CalendarSymbolId'
        trips:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeTrip'
        events:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeEvent'

    BrigadeResource:
      type: object
      properties:
        sequence:
          type: integer
        sequenceHex:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeEvent'

    BrigadeBodyV2:
      type: object
      properties:
        brigadeName:
          type: string
        calendarSymbolId:
          $ref: '../public-transport-core.yaml#/components/schemas/CalendarSymbolId'
        calendarDesignation:
          type: string
        calendarDescription:
          type: string
        brigadeResources:
          type: array
          items:
            $ref: '#/components/schemas/BrigadeResource'

    BrigadePatchBody:
      type: object
      properties:
        brigadePayload:
          $ref: '#/components/schemas/BrigadePayload'
        brigadeBody:
          $ref: '#/components/schemas/BrigadeBody'

    BrigadePayload:
      type: object
      properties:
        brigadeName:
          type: string
        calendarSymbolId:
          $ref: '../public-transport-core.yaml#/components/schemas/CalendarSymbolId'

    BrigadeDeleteBody:
      type: object
      properties:
        brigadeName:
          type: string
