openapi: 3.0.0
info:

paths:
  /agency/{agency}/timetable-generator:
    get:
      tags:
        - timetable-generator
      summary: Get list all generated timetables
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimetableGeneratorPayload'

    post:
      tags:
        - timetable-generator
      summary: Create new timetable generator
      operationId: createTimetableGenerator
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTimetableGeneratorRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTimetableGeneratorRequest'

    put:
      tags:
        - timetable-generator
      summary: Update already existed timetable
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:

    delete:
      tags:
        - timetable-generator
      summary: Delete generated summary
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:

  /agency/{agency}/timetable-generator/routes:
    get:
      tags:
        - timetable-generator
      summary: Get list all generated timetables
      operationId: findRoutes
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimetableGeneratorFilterByRoutesResponse'

  /agency/{agency}/timetable-generator/trips:
    post:
      tags:
        - timetable-generator
      summary: Get front and back trips
      operationId: findTrips
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TripFilter'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripResponse'


  /agency/{agency}/timetable-generator/calendars:
    get:
      tags:
        - timetable-generator
      summary: Get list all generated timetables
      operationId: findCalendars
      parameters:
        - in: path
          name: agency
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimetablePayload'

components:
  schemas:

    RouteId:
      type: object
      properties:
        name:
          type: string
        line:
          type: string

    TripFilter:
      type: object
      properties:
        routeId:
          $ref: '#/components/schemas/RouteId'

    TimetableTrip:
      type: object
      properties:
        tripId:
          $ref: '../public-transport-api.yaml/#/components/schemas/TripId'
        designation:
          type: string
        description:
          type: string

    TripResponse:
      type: object
      properties:
        routeFilter:
          $ref: '#/components/schemas/RouteId'
        front:
          type: array
          items:
            $ref: '#/components/schemas/TimetableTrip'
        back:
          type: array
          items:
            $ref: '#/components/schemas/TimetableTrip'

    TimetableStopTime:
      type: object
      properties:
        time:
          type: string
        designation:
          type: string

    TimetablePayload:
      type: object
      properties:
        startDate:
          type: string
        endDate:
          type: string
        interval:
          type: string
        departures:
          type: array
          items:
            $ref: '#/components/schemas/TimetableStopTime'

    TimetableGeneratorPayload:
      type: object
      properties:
        calendarName:
          type: string
        front:
          $ref: '#/components/schemas/TimetablePayload'
        back:
          $ref: '#/components/schemas/TimetablePayload'

    CreateTimetableGeneratorRequest:
      type: object
      properties:
        routeId:
          $ref: '#/components/schemas/RouteId'
        timetables:
          $ref: '#/components/schemas/TimetableGeneratorPayload'

    TimetableGeneratorFilterByRoutes:
      type: object
      properties:
        routeId:
          $ref: '#/components/schemas/RouteId'

    TimetableGeneratorFilterByRoutesResponse:
      type: object
      properties:
        page:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/TimetableGeneratorFilterByRoutes'

    TimetableGeneratorFilterByCalendar:
      type: object
      properties:

