databaseChangeLog:
  - changeSet:
      id: create-table-app-user
      author: pwrona
      changes:
        - createSequence:
            sequenceName: app_user_id_seq
            startValue: 1
            incrementBy: 1

        - createTable:
            tableName: app_user
            columns:
              - column:
                  name: app_user_id
                  type: integer
                  defaultValueSequenceNext: app_user_id_seq
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: varchar(30)
                  constraints:
                    unique: true
              - column:
                  name: email
                  type: varchar(30)
                  constraints:
                    unique: true
              - column:
                  name: password
                  type: varchar(60)
              - column:
                  name: created_at
                  type: datetime
              - column:
                  name: updated_at
                  type: datetime
              - column:
                  name: account_non_expired
                  type: boolean
              - column:
                  name: account_non_locked
                  type: boolean
              - column:
                  name: credentials_non_expired
                  type: boolean
              - column:
                  name: enabled
                  type: boolean

  - changeSet:
      id: create-table-app-role
      author: pwrona
      changes:
        - createTable:
            tableName: app_role
            columns:
              - column:
                  name: app_role_id
                  type: varchar(15)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: description
                  type: varchar(255)

        - createTable:
            tableName: app_user_app_role
            columns:
              - column:
                  name: app_user_id
                  type: integer
                  constraints:
                    nullable: false
                    foreignKeyName: fk_app_user_app_role_app_user
                    references: app_user(app_user_id)
              - column:
                  name: app_role_id
                  type: varchar(15)
                  constraints:
                    nullable: false
                    foreignKeyName: fk_app_user_app_role_app_role
                    references: app_role(app_role_id)
