openapi: 3.0.3
info:
  title: Accounts API
  version: 1.0.0

paths:
  /accounts:
    get:
      summary: Get list of accounts
      responses:
        '200':
          description: Successful response with accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'

components:
  schemas:
    AccountsResponse:
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'

    Account:
      type: object
      required:
        - id
        - name
        - accountNumber
        - holderName
        - owner
        - balance
        - currency
        - links
      properties:
        id:
          type: string
          format: uuid
          example: 2e6285c2-061d-4305-afc5-c95db6f32d2c
        name:
          type: string
          example: Melody's current account
        accountNumber:
          type: string
          example: PL08326970647073934234269811
        holderName:
          type: string
          example: Melody Parisian
        owner:
          $ref: '#/components/schemas/Owner'
        balance:
          type: string
          description: Account balance represented as a string
          example: "2082570.96"
        currency:
          type: string
          example: EUR
        links:
          $ref: '#/components/schemas/AccountLinks'

    Owner:
      type: object
      required:
        - firstName
        - lastName
        - address
      properties:
        firstName:
          type: string
          example: Melody
        lastName:
          type: string
          example: Parisian
        address:
          $ref: '#/components/schemas/Address'

    Address:
      type: object
      required:
        - street
        - postcode
        - city
      properties:
        street:
          type: string
          example: 110 Hoyt Light
        postcode:
          type: string
          example: "88330"
        city:
          type: string
          example: Harryburgh

    AccountLinks:
      type: object
      required:
        - transactions
        - info
      properties:
        transactions:
          type: string
          example: /2e6285c2-061d-4305-afc5-c95db6f32d2c/transactions?from=2025-12-23&days=30
        info:
          type: string
          example: /2e6285c2-061d-4305-afc5-c95db6f32d2c
