---
certbot_snap_classic: true
certbot_domains: []
certbot_email: ""
certbot_webroot: /var/www/certbot
# Use Let's Encrypt staging while testing (avoids rate limits)
certbot_staging: false
app_root_dir: /opt/public-transport
docker_apt_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
