apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-transport-web-server
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: public-transport-web-server
        image: registry.digitalocean.com/igeolab/igeolab/public-transport-web-server:1.0.0
        ports:
        - containerPort: 8080
