apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-transport-web-server
  labels:
    app: public-transport-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-transport-web-server
  template:
    metadata:
      labels:
        app: public-transport-web-server
    spec:
      containers:
        - name: public-transport-web-server
          image: registry.digitalocean.com/igeolab/igeolab/public-transport-web-server:1.0.0
          ports:
            - containerPort: 80
