apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: public-transport-web-server
          image: igeolab/public-transport-web-server:1.0.0
          ports:
            - containerPort: 8080
