apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-transport-web-deployment
  labels:
    app: public-transport-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-transport-web
  template:
    metadata:
      labels:
        app: public-transport-web
    spec:
      containers:
        - name: public-transport-web
          image: igeolab/public-transport-web-server:1.0.0
          ports:
            - containerPort: 8080
