apiVersion: v1
kind: Service
metadata:
  name: public-transport-web-server-service
  labels:
    name: web
    app: web
spec:
  ports:
    - port: 80
      targetPort: 8080
    selector:
      name: web
      app: web

