name: Build and test

on:
  workflow_dispatch:
    inputs:
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build Artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build Backend App ${{ inputs.artifact }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          cd ${{ inputs.artifact }}
          mvn clean verify
        
