name: Deploy Docker

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: Artifact ID
        options:
          - public-transport-web-server

env:
  REGISTRY: registry.digitalocean.com/igeolab

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Angular App
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          cd public-transport-web-client
          npm install
          npm run generate
          npm run build

      - name: Build Backend App ${{ inputs.artifact }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          cd ${{ inputs.artifact }}
          mvn clean install

      - name: Dump GitHub context
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#      - name: Build docker ${{ input.artifact }}
#        run: cd ${{ input.artifact }} && docker build -t igeolab/public-transport-web:latest .
#
#      - name: Tag Image
#        run: docker tag igeolab/${{ inputs.artifact }}:latest ${{env.REGISTRY}}/igeolab/${{ inputs.artifact }}:latest
#
#      - name: Log in to DigitalOcean Container Registry with short-lived credentials
#        run: doctl registry login --expiry-seconds 1200
#
#      - name: Deploy docker image
#        run: docker push ${{env.REGISTRY}}/igeolab/${{ inputs.artifact }}:latest
