name: 🚀 Deploy website

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose where you want to publish the build'
        required: true
        default: prod
        type: choice
        options:
          - dev
          - prod
  pull_request:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          cd public-transport-web-client
          npm install
          npm run public-transport-api:generate
          npm run public-transport-pdf-api:generate
          ls ./src/app/generated/public-transport-pdf -la
#          npm run public-transport-pdf-api:sed
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.samkirkland.com
          username: myFtpUserName
          password: ${{ secrets.password }}