name: Deploy traccar config on Droplet and restart Docker containers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose where you want to publish the build'
        required: true
        default: 'traccar-dev'
        type: choice
        options:
          - traccar-dev

env:
  APP_DIR: /opt/traccar

jobs:
  droplet:
    name: Sync docker-compose on Droplet
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: YAML Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'docker-compose.traccar.yml'
        env:
          services.database.environment.POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          services.database.environment.POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Stop containers if docker-compose exists on Droplet
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -euo pipefail
            mkdir -p "${{ env.APP_DIR }}"
            cd "${{ env.APP_DIR }}"

            if [ -f docker-compose.traccar.yml ]; then
              echo "docker-compose found in ${{ env.APP_DIR }}, stopping containers"
              docker compose -f docker-compose.traccar.yml down
            else
              echo "docker-compose not found in ${{ env.APP_DIR }}, it will be copied from GitHub"
            fi

      - name: Overwrite docker-compose.traccar.yml from GitHub repository
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: docker-compose.traccar.yml
          target: ${{ env.APP_DIR }}
          overwrite: true

      - name: Copy nginx config to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: nginx/${{ inputs.environment }}/*
          target: ${{ env.APP_DIR }}/nginx
          strip_components: 2
          overwrite: true

      - name: Start docker compose on Droplet
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -euo pipefail
            cd "${{ env.APP_DIR }}"
            docker compose -f docker-compose.traccar.yml up -d
