name: 🚀 Deploy website

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose where you want to publish the build'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - prod

env:
  WEB_MODULE_NAME: public-transport-web-client

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          cd ${{ env.WEB_MODULE_NAME }}
          npm install
          npm run generate
          npm run public-transport-api:generate
          npm run public-transport-pdf-api:generate
          npm run public-transport-pdf-api:sed
          npm run public-transport-pdf-api:sed:recursive
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_NAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./${{ env.WEB_MODULE_NAME }}/build/browser/
          server-dir: ./www/