name: Deploy Docker

on:
  workflow_dispatch:
    inputs:

env:
  REGISTRY: registry.digitalocean.com/igeolab

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Angular App
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          cd ./public-transport-web-client
          npm install
          npm run generate
          npm run build
