on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string

jobs:
  unit:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Test ${{ inputs.artifact }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          cd ${{ inputs.artifact }}
          mvn clean verify
