on:
  workflow_call:
    inputs:
      artifact:
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: false

env:
  REGISTRY: registry.digitalocean.com/igeolab
  ARTIFACT: igeolab/public-transport-web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download app jar
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ${{ inputs.artifact }}/target

      - name: ls target
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          cd ${{ inputs.artifact }}
          ls -lh

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#        - name: Build docker ${{ inputs.artifact }}
#          run: cd ${{ inputs.artifact }} && docker build -t ${{ env.ARTIFACT }}:latest .
#
#        - name: Tag Image
#          run: docker tag ${{ env.ARTIFACT }}:latest ${{ env.REGISTRY }}/${{ env.ARTIFACT }}:latest
#
#        - name: Log in to DigitalOcean Container Registry with short-lived credentials
#          run: doctl registry login --expiry-seconds 1200
#
#        - name: Deploy docker image
#          run: docker push ${{ env.REGISTRY }}/${{ env.ARTIFACT }}:latest
