on:
  workflow_call:
    inputs:
      artifact:
        type: string

env:
  REGISTRY: registry.digitalocean.com/igeolab
  ARTIFACT: igeolab/public-transport-web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
