name: Deploy master

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/job-test-workflow.yml
    with:
      artifact: public-transport-web-server
