name: Deploy master

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on:
      name: Build Artifact
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
