name: Test branch

on:
  pull_request:
    branches:
      - !master

jobs:
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/job-test-workflow.yml
    with:
      artifact: public-transport-web-server
